### ISSUE TITLE
Stylizer causes some emotes to not work

### ISSUE THREAD

**Issue by InSimpleTermsJordan** [tag9724/Scrap.tf-stylizer#1]
Emotes such as :edgy: will work until the stylizer loads, then they'll display the "missing texture" icon as if the emote didn't exist. Disabling the stylizer allows the emotes to load correctly.

**Comment by tag9724** [comment]
Okay thanks it's fixed now, just needed to update the scraptf emote list
https://scrap.tf/img/emotes/
